glx/windows: Avoid shadowing 'type' parameter of driwindowsCreateDrawable()
> ../src/glx/driwindows_glx.c: In function ‘driwindowsCreateDrawable’:
> ../src/glx/driwindows_glx.c:283:17: error: ‘type’ redeclared as different kind of symbol
>  283 |    unsigned int type;
>      |                 ^~~~
> ../src/glx/driwindows_glx.c:261:52: note: previous definition of ‘type’ with type ‘int’
>   261 |                          GLXDrawable drawable, int type,
>      |                                                ~~~~^~~~

Fixes: 887f5a632046 ("glx: add drawable type argument when create drawable")
Signed-off-by: Jon Turney <jon.turney@dronecode.org.uk>
(cherry picked from commit f9a7c50ed6ff89414247929b2d4b52e32c5c9350)

Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/41829>