glx/windows: Drop static from driwindowsCreateScreen()
> ../src/glx/driwindows_glx.c:445:1: error: static declaration of ‘driwindowsCreateScreen’ follows non-static declaration
>   445 | driwindowsCreateScreen(int screen, struct glx_display *priv, bool driver_name_is_inferred)
> ../src/glx/glxclient.h:160:20: note: previous declaration of ‘driwindowsCreateScreen’ with type ‘struct glx_screen *(int,  struct glx_display *, _Bool)’
>   160 | struct glx_screen *driwindowsCreateScreen(int screen, struct glx_display *priv, bool driver_name_is_inferred);

Since driwindowsCreateScreen() is now called directly, rather than via
function pointers in the _GLXDRIdisplay structure, it needs to be
public.

Fixes: 0d78711cfb9f ("glx: delete __GLXDRIdisplay")
Signed-off-by: Jon Turney <jon.turney@dronecode.org.uk>
(cherry picked from commit 90c47206c598fb27b3af97a543d0ca87dd79af85)

Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/41676>