glx/windows: Fix compliation after code motion to put event base in 'dri' context
> ../src/glx/driwindows_glx.c: In function ‘driwindowsCreateScreen’:
> ../src/glx/driwindows_glx.c:479:48: error: ‘dpy’ undeclared (first use in this function)

08e2985e5743 moved this code from driwindowsCreateDisplay to
driwindowsCreateScreen.

Unfortunately, dpy is no longer a parameter, so we need to look it up in
glx_display struct. (Looking it up in psc->base before it's initialized
here initialized would be incorrect).

Fixes: 08e2985e5743 ("glx: move driwindows_display::event_base to driwindows_context")
Signed-off-by: Jon Turney <jon.turney@dronecode.org.uk>
(cherry picked from commit db26f345301fb0559afecd4e1aa38655f1c6e1c3)

Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/41676>