drm-shim/freedreno: Fix fprintf format specifier
```
../freedreno_noop.c:329:15: error: format specifies type
'unsigned long' but the argument has type 'uint64_t'
(aka 'unsigned long long') [-Werror,-Wformat]
```

Fixes: 920a93170db ("freedreno/drm-shim: allow chip selection by chip_id")
Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/42661>