rusticl: skip bindgen for pipe_shader_state_from_tgsi
bindgen up to at least 0.72.1 generates invalid code (see below) and
that function is not used, so simply skip it.

    src/gallium/frontends/rusticl/rusticl_mesa_bindings.c:795:81: error: duplicate ‘const’ declaration specifier [-Werror=duplicate-decl-specifier]
      795 | void pipe_shader_state_from_tgsi__extern(struct pipe_shader_state *state, const const struct tgsi_token *tokens) { pipe_shader_state_from_tgsi(state, tokens); }
          |                                                                                 ^~~~~

Backport-to: *
(cherry picked from commit 09ea05cf23fc6d116d18490569f13f010f790833)

Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/42298>