gfxstream/platform: add missing inc_include to platform_virtgpu build
src/gfxstream/guest/platform/VirtGpu.cpp
| In file included from ../sources/mesa-26.0.6.imx/src/util/os_misc.h:42,
|                  from ../sources/mesa-26.0.6.imx/src/gfxstream/guest/platform/VirtGpu.cpp:12:
| ../sources/mesa-26.0.6.imx/src/util/u_math.h:42:10: fatal error: c99_compat.h: No such file or directory
|    42 | #include "c99_compat.h"
|       |          ^~~~~~~~~~~~~~
| compilation terminated.

Fixes: 5826a0a ("gfxstream: meson format -i {all meson files}")

Signed-off-by: Ryan Zhang <ryan.zhang@nxp.com>
Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/41978>